[phases.frontend]
nixPkgs = ["nodejs_20"]
cmds = [
    "cd frontend && npm install && npm run build && cd .."
]

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
